#Anything that is optional which you are not using, just delete that line. You can also delete any of the '#comments'
 
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="MIT License" #mandatory https://choosealicense.com/
issueTrackerURL="https://github.com/Pepperized/strippers/issues" #optional
 
[[mods]] #mandatory
modId="strippers" #mandatory
version="v1" #mandatory
displayName="Strippers" #mandatory
displayURL="https://github.com/Pepperized/strippers" #optional
credits="The credits for your mod." #optional
authors="Pepperized" #optional
description='''
Automatic log stripping machines.
''' #mandatory
 